### ISSUE TITLE
Log IP address for each order

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/api-plugin-orders#11]
@eziel commented on [Sat Feb 17 2018](https://github.com/reactioncommerce/reaction/issues/3777)

Having the IP address from the computer creating the order could be very helpful for fraud detection and analysis. please add a field to the order collection with the users IP address.

Thank you.

**Comment by rondlite** [comment]
Better close this if an IP address is not allowed  as per PR comment. We will fork plugin to obey European laws.

**Comment by brent-hoover** [comment]
Well my comment was meant that the correct path would be to add any additional fields you need in a custom plugin that extends the schema not a fork of this one. Will that not work?

**Comment by rondlite** [comment]
Would work, however the order plugin already handles names address phone number. So the logic is beyond my comprehension. Specially since it is a legal requirement.

**Comment by brent-hoover** [comment]
Generally I think our approach with fields would not be to try and have every field that everyone might need but the minimum amount of fields that are necessary and an easy way for people to extend with additional fields that are required by their use case

**Comment by brent-hoover** [comment]
Although it might be required in some countries it is not in others, and although it's an optional field sort of making it a sanctioned field while the legal ramifications are not well understood doesn't seem like a good idea when there is a clear and easy path to adding it through extension where each implementation can make sure the data has been properly T&C'd.

If someone can make a clear case there there are no countries where this would ever cause any unwanted PII ramifications I would love to make this change and reopen this issue as I agree that this would be a very handy field to have that a lot of people could benefit from.

**Comment by brent-hoover** [comment]
The difference with name and address is that those are given freely, whereas IP address is taken silently without the users consent.

**Comment by rondlite** [comment]
Yes, but at a point where the user is placing an order. 
By placing an order you should have to accept the websites privacy policy. 
However collecting IP is law and has nothing to do with consent. 
Please tell me which countries do not have this law, since some hacker friends might like to order stuff there.

Github itself complies:
Please note that GitHub may collect User Personal Information from visitors to your GitHub Pages website, including logs of visitor IP addresses, to comply with legal obligations, and to maintain the security and integrity of the Website and the Service.
